version: "3.7"
services:
#
  db:
    image: postgres:latest
    volumes:
      - hapmap-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: HapMap
    restart: unless-stopped

  stable_app:
    build: .
    container_name: HapMapDjango
    volumes:
      - static:/code/HapMap/static
      - media:/code/HapMap/media
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn HapMap.wsgi --bind 0.0.0.0:8001 --workers=2"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DEV=False
      - DEBUG=True
    ports:
      - 8001:8001

#  hapamp-data-ftp:
#    image: stilliard/pure-ftpd:hardened
#    ports:
#      - "21:21"
#      - "30000-30009:30000-30009"
#    volumes:
#      - static:/home/username/static
#      - media:/home/username/media
#      - ftp-data:/etc/pure-ftpd/passwd
#    environment:
#      PUBLICHOST: "localhost"
#      FTP_USER_NAME: root
#      FTP_USER_PASS: password
#      FTP_USER_HOME: /home/username
#      FTP_USER_UID: 0
#      FTP_USER_GID: 0
#
#    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  hapmap-db-data:
  static:
  media:
  ftp-data:
