version: "3.7"
services:

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  stable_app:
    image: dmatthijz98/hap-map:latest
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db


  stable_dev:
    image: dmatthijz98/hap-map:dev
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

networks:
  frontend:
  backend:

volumes:
  db-data: