version: "3.7"
services:

  db:
    image: postgres:latest
    volumes:
      - hapmap-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: HapMap
    restart: unless-stopped

  stable_app:
    volumes:
      - hapmap-data:/static/HapMap/img
    image: matthijz98/hap-map:latest
    ports:
      - "8001:8001"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DEV=False
      - DEBUG=False

  stable_dev:
    image: matthijz98/hap-map:dev
    volumes:
      - hapmap-data:/static/HapMap/img
    ports:
      - "8002:8002"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DEV=False
      - DEBUG=True

volumes:
  hapmap-db-data:
  hapmap-data:
