version: "3.7"
services:

  db:
    image: postgres:latest
    volumes:
      - hapmap-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: HapMapWachtwoord
      POSTGRES_DB: HapMap


  stable_app:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    links:
      - db:db


  stable_dev:
    image: matthijz98/hap-map:dev
    ports:
      - "8001:8001"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - db
    links:
      - db:db

volumes:
  hapmap-db-data: