// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CamplistsApiGetKamplijstData, CamplistsApiGetKamplijstResponses, CamplistsApiListKamplijstsData, CamplistsApiListKamplijstsResponses, IngredientsApiGetAllergiesData, IngredientsApiGetAllergiesResponses, IngredientsApiGetIngredientDetailData, IngredientsApiGetIngredientDetailResponses, IngredientsApiGetIngredientsData, IngredientsApiGetIngredientsResponses, RecipesApiPublicGetCategoriesData, RecipesApiPublicGetCategoriesResponses, RecipesApiPublicGetRecipeDetailData, RecipesApiPublicGetRecipeDetailResponses, RecipesApiPublicGetRecipesData, RecipesApiPublicGetRecipesResponses, RecipesApiPublicSearchRecipesData, RecipesApiPublicSearchRecipesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Ingredients
 */
export const ingredientsApiGetIngredients = <ThrowOnError extends boolean = false>(options?: Options<IngredientsApiGetIngredientsData, ThrowOnError>) => (options?.client ?? client).get<IngredientsApiGetIngredientsResponses, unknown, ThrowOnError>({ url: '/ingredients/', ...options });

/**
 * Get Ingredient Detail
 */
export const ingredientsApiGetIngredientDetail = <ThrowOnError extends boolean = false>(options: Options<IngredientsApiGetIngredientDetailData, ThrowOnError>) => (options.client ?? client).get<IngredientsApiGetIngredientDetailResponses, unknown, ThrowOnError>({ url: '/ingredients/{sqid}/', ...options });

/**
 * Get Allergies
 */
export const ingredientsApiGetAllergies = <ThrowOnError extends boolean = false>(options?: Options<IngredientsApiGetAllergiesData, ThrowOnError>) => (options?.client ?? client).get<IngredientsApiGetAllergiesResponses, unknown, ThrowOnError>({ url: '/allergies/', ...options });

/**
 * Get Recipes
 */
export const recipesApiPublicGetRecipes = <ThrowOnError extends boolean = false>(options?: Options<RecipesApiPublicGetRecipesData, ThrowOnError>) => (options?.client ?? client).get<RecipesApiPublicGetRecipesResponses, unknown, ThrowOnError>({ url: '/recipes/', ...options });

/**
 * Get Recipe Detail
 */
export const recipesApiPublicGetRecipeDetail = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPublicGetRecipeDetailData, ThrowOnError>) => (options.client ?? client).get<RecipesApiPublicGetRecipeDetailResponses, unknown, ThrowOnError>({ url: '/recipes/{sqid}/', ...options });

/**
 * Search Recipes
 */
export const recipesApiPublicSearchRecipes = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPublicSearchRecipesData, ThrowOnError>) => (options.client ?? client).post<RecipesApiPublicSearchRecipesResponses, unknown, ThrowOnError>({ url: '/recipes/search/', ...options });

/**
 * Get Categories
 */
export const recipesApiPublicGetCategories = <ThrowOnError extends boolean = false>(options?: Options<RecipesApiPublicGetCategoriesData, ThrowOnError>) => (options?.client ?? client).get<RecipesApiPublicGetCategoriesResponses, unknown, ThrowOnError>({ url: '/categories/', ...options });

/**
 * List Kamplijsts
 */
export const camplistsApiListKamplijsts = <ThrowOnError extends boolean = false>(options?: Options<CamplistsApiListKamplijstsData, ThrowOnError>) => (options?.client ?? client).get<CamplistsApiListKamplijstsResponses, unknown, ThrowOnError>({ url: '/camplist/', ...options });

/**
 * Get Kamplijst
 */
export const camplistsApiGetKamplijst = <ThrowOnError extends boolean = false>(options: Options<CamplistsApiGetKamplijstData, ThrowOnError>) => (options.client ?? client).get<CamplistsApiGetKamplijstResponses, unknown, ThrowOnError>({ url: '/camplist/{sqid}/', ...options });
