// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * AllergyOutSchema
 */
export type AllergyOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * IngredientOutSchema
 */
export type IngredientOutSchema = {
    /**
     * Allergies
     */
    allergies?: Array<AllergyOutSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name Singular
     */
    name_singular: string;
    /**
     * Name Plural
     */
    name_plural: string;
};

/**
 * RecipeFilterSchema
 */
export type RecipeFilterSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Created By
     */
    created_by?: string | null;
};

/**
 * CreatorProfileOutSchema
 */
export type CreatorProfileOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Profile Icon
     */
    profile_icon: string;
    /**
     * Profile Picture Small
     */
    profile_picture_small: string;
    /**
     * Profile Picture Large
     */
    profile_picture_large: string;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Url
     */
    url?: string | null;
};

/**
 * RecipeCategoryOutSchema
 */
export type RecipeCategoryOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * RecipeListOutSchema
 */
export type RecipeListOutSchema = {
    category: RecipeCategoryOutSchema;
    /**
     * Includes Allergies
     */
    includes_allergies?: Array<AllergyOutSchema> | null;
    created_by: CreatorProfileOutSchema;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Short Description
     */
    short_description?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AlternativeOutSchema
 */
export type AlternativeOutSchema = {
    alternative_ingredient: IngredientOutSchema;
    /**
     * For Allergies
     */
    for_allergies?: Array<AllergyOutSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit
     */
    unit?: string | null;
};

/**
 * RecipeIngredientOutSchema
 */
export type RecipeIngredientOutSchema = {
    ingredient: IngredientOutSchema;
    /**
     * Ingredient Alternatives
     */
    ingredient_alternatives?: Array<AlternativeOutSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit
     */
    unit: string;
};

/**
 * RecipeNoteOutSchema
 */
export type RecipeNoteOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Note
     */
    note: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Order
     */
    order?: number;
};

/**
 * RecipeOutSchema
 */
export type RecipeOutSchema = {
    /**
     * Includes Allergies
     */
    includes_allergies?: Array<AllergyOutSchema>;
    /**
     * Steps
     */
    steps?: Array<RecipeStepOutSchema>;
    category: RecipeCategoryOutSchema;
    /**
     * Notes
     */
    notes?: Array<RecipeNoteOutSchema>;
    /**
     * Ingredients
     */
    ingredients?: Array<RecipeIngredientOutSchema>;
    created_by: CreatorProfileOutSchema;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Short Description
     */
    short_description?: string | null;
};

/**
 * RecipeStepOutSchema
 */
export type RecipeStepOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Order
     */
    order: number;
    /**
     * Instruction
     */
    instruction: string;
};

export type IngredientsApiGetIngredientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ingredients/';
};

export type IngredientsApiGetIngredientsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<IngredientOutSchema>;
};

export type IngredientsApiGetIngredientsResponse = IngredientsApiGetIngredientsResponses[keyof IngredientsApiGetIngredientsResponses];

export type IngredientsApiGetIngredientDetailData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/ingredients/{sqid}/';
};

export type IngredientsApiGetIngredientDetailResponses = {
    /**
     * OK
     */
    200: IngredientOutSchema;
};

export type IngredientsApiGetIngredientDetailResponse = IngredientsApiGetIngredientDetailResponses[keyof IngredientsApiGetIngredientDetailResponses];

export type IngredientsApiGetAllergiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/allergies/';
};

export type IngredientsApiGetAllergiesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<AllergyOutSchema>;
};

export type IngredientsApiGetAllergiesResponse = IngredientsApiGetAllergiesResponses[keyof IngredientsApiGetAllergiesResponses];

export type RecipesApiPublicGetRecipesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name
         */
        name?: string | null;
        /**
         * Created By
         */
        created_by?: string | null;
    };
    url: '/recipes/';
};

export type RecipesApiPublicGetRecipesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<RecipeListOutSchema>;
};

export type RecipesApiPublicGetRecipesResponse = RecipesApiPublicGetRecipesResponses[keyof RecipesApiPublicGetRecipesResponses];

export type RecipesApiPublicGetRecipeDetailData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/recipes/{sqid}/';
};

export type RecipesApiPublicGetRecipeDetailResponses = {
    /**
     * OK
     */
    200: RecipeOutSchema;
};

export type RecipesApiPublicGetRecipeDetailResponse = RecipesApiPublicGetRecipeDetailResponses[keyof RecipesApiPublicGetRecipeDetailResponses];

export type RecipesApiPublicSearchRecipesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
    };
    url: '/recipes/search/';
};

export type RecipesApiPublicSearchRecipesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipesApiPublicGetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories/';
};

export type RecipesApiPublicGetCategoriesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<RecipeCategoryOutSchema>;
};

export type RecipesApiPublicGetCategoriesResponse = RecipesApiPublicGetCategoriesResponses[keyof RecipesApiPublicGetCategoriesResponses];

export type CamplistsApiListKamplijstsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/camplist/';
};

export type CamplistsApiListKamplijstsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CamplistsApiGetKamplijstData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/camplist/{sqid}/';
};

export type CamplistsApiGetKamplijstResponses = {
    /**
     * OK
     */
    200: unknown;
};
