// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { RecipesApiPrivateCreateIngredientData, RecipesApiPrivateCreateIngredientResponses, RecipesApiPrivateCreatePrivateRecipeData, RecipesApiPrivateCreatePrivateRecipeResponses, RecipesApiPrivateDeletePrivateRecipeData, RecipesApiPrivateDeletePrivateRecipeResponses, RecipesApiPrivateGetPrivateRecipeDetailData, RecipesApiPrivateGetPrivateRecipeDetailResponses, RecipesApiPrivateListPrivateRecipesData, RecipesApiPrivateListPrivateRecipesResponses, RecipesApiPrivateUpdatePrivateRecipeData, RecipesApiPrivateUpdatePrivateRecipeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Private Recipes
 */
export const recipesApiPrivateListPrivateRecipes = <ThrowOnError extends boolean = false>(options?: Options<RecipesApiPrivateListPrivateRecipesData, ThrowOnError>) => (options?.client ?? client).get<RecipesApiPrivateListPrivateRecipesResponses, unknown, ThrowOnError>({ url: '/private/recipes/recipes/', ...options });

/**
 * Create Private Recipe
 */
export const recipesApiPrivateCreatePrivateRecipe = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPrivateCreatePrivateRecipeData, ThrowOnError>) => (options.client ?? client).post<RecipesApiPrivateCreatePrivateRecipeResponses, unknown, ThrowOnError>({
    querySerializer: { parameters: { recipe_data: { object: { style: 'form' } } } },
    url: '/private/recipes/recipes/',
    ...options
});

/**
 * Delete Private Recipe
 */
export const recipesApiPrivateDeletePrivateRecipe = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPrivateDeletePrivateRecipeData, ThrowOnError>) => (options.client ?? client).delete<RecipesApiPrivateDeletePrivateRecipeResponses, unknown, ThrowOnError>({ url: '/private/recipes/recipes/{sqid}/', ...options });

/**
 * Get Private Recipe Detail
 */
export const recipesApiPrivateGetPrivateRecipeDetail = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPrivateGetPrivateRecipeDetailData, ThrowOnError>) => (options.client ?? client).get<RecipesApiPrivateGetPrivateRecipeDetailResponses, unknown, ThrowOnError>({ url: '/private/recipes/recipes/{sqid}/', ...options });

/**
 * Update Private Recipe
 */
export const recipesApiPrivateUpdatePrivateRecipe = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPrivateUpdatePrivateRecipeData, ThrowOnError>) => (options.client ?? client).put<RecipesApiPrivateUpdatePrivateRecipeResponses, unknown, ThrowOnError>({
    url: '/private/recipes/recipes/{sqid}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create Ingredient
 */
export const recipesApiPrivateCreateIngredient = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPrivateCreateIngredientData, ThrowOnError>) => (options.client ?? client).post<RecipesApiPrivateCreateIngredientResponses, unknown, ThrowOnError>({
    url: '/private/recipes/ingredients/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
