// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * PrivateAllergyOutSchema
 */
export type PrivateAllergyOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * PrivateIngredientOutSchema
 */
export type PrivateIngredientOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name Singular
     */
    name_singular: string;
    /**
     * Name Plural
     */
    name_plural: string;
};

/**
 * PrivateRecipeCategorieOutSchema
 */
export type PrivateRecipeCategorieOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * PrivateRecipeIngredientAltForAllergyOutSchema
 */
export type PrivateRecipeIngredientAltForAllergyOutSchema = {
    /**
     * For Allergies
     */
    for_allergies?: Array<PrivateAllergyOutSchema>;
    alternative_ingredient: PrivateIngredientOutSchema;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit
     */
    unit?: string | null;
};

/**
 * PrivateRecipeIngredientOutSchema
 */
export type PrivateRecipeIngredientOutSchema = {
    ingredient: PrivateIngredientOutSchema;
    /**
     * Ingredient Alternatives
     */
    ingredient_alternatives?: Array<PrivateRecipeIngredientAltForAllergyOutSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit
     */
    unit: string;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * PrivateRecipeOutSchema
 */
export type PrivateRecipeOutSchema = {
    category: PrivateRecipeCategorieOutSchema;
    /**
     * Steps
     */
    steps?: Array<PrivateRecipeStepOutSchema>;
    /**
     * Ingredients
     */
    ingredients?: Array<PrivateRecipeIngredientOutSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Short Description
     */
    short_description?: string | null;
};

/**
 * PrivateRecipeStepOutSchema
 */
export type PrivateRecipeStepOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Order
     */
    order: number;
    /**
     * Instruction
     */
    instruction: string;
};

/**
 * AllergyOutSchema
 */
export type AllergyOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * IngredientOutSchema
 */
export type IngredientOutSchema = {
    /**
     * Allergies
     */
    allergies?: Array<AllergyOutSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name Singular
     */
    name_singular: string;
    /**
     * Name Plural
     */
    name_plural: string;
};

export type RecipesApiPrivateListPrivateRecipesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/private/recipes/recipes/';
};

export type RecipesApiPrivateListPrivateRecipesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipesApiPrivateCreatePrivateRecipeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Recipe Data
         */
        recipe_data: {
            [key: string]: unknown;
        };
    };
    url: '/private/recipes/recipes/';
};

export type RecipesApiPrivateCreatePrivateRecipeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipesApiPrivateDeletePrivateRecipeData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/private/recipes/recipes/{sqid}/';
};

export type RecipesApiPrivateDeletePrivateRecipeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipesApiPrivateGetPrivateRecipeDetailData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/private/recipes/recipes/{sqid}/';
};

export type RecipesApiPrivateGetPrivateRecipeDetailResponses = {
    /**
     * OK
     */
    200: PrivateRecipeOutSchema;
};

export type RecipesApiPrivateGetPrivateRecipeDetailResponse = RecipesApiPrivateGetPrivateRecipeDetailResponses[keyof RecipesApiPrivateGetPrivateRecipeDetailResponses];

export type RecipesApiPrivateUpdatePrivateRecipeData = {
    body: PrivateRecipeOutSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/private/recipes/recipes/{sqid}/';
};

export type RecipesApiPrivateUpdatePrivateRecipeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipesApiPrivateCreateIngredientData = {
    body: IngredientOutSchema;
    path?: never;
    query?: never;
    url: '/private/recipes/ingredients/';
};

export type RecipesApiPrivateCreateIngredientResponses = {
    /**
     * OK
     */
    200: unknown;
};
