// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * PrivateAllergyOutSchema
 */
export type PrivateAllergyOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * PrivateIngredientOutSchema
 */
export type PrivateIngredientOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name Singular
     */
    name_singular: string;
    /**
     * Name Plural
     */
    name_plural: string;
};

/**
 * PrivateRecipeCategorieOutSchema
 */
export type PrivateRecipeCategorieOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * PrivateRecipeIngredientAltForAllergyOutSchema
 */
export type PrivateRecipeIngredientAltForAllergyOutSchema = {
    /**
     * For Allergies
     */
    for_allergies?: Array<PrivateAllergyOutSchema>;
    alternative_ingredient: PrivateIngredientOutSchema;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit
     */
    unit?: string | null;
};

/**
 * PrivateRecipeIngredientOutSchema
 */
export type PrivateRecipeIngredientOutSchema = {
    ingredient: PrivateIngredientOutSchema;
    /**
     * Ingredient Alternatives
     */
    ingredient_alternatives?: Array<PrivateRecipeIngredientAltForAllergyOutSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * PrivateRecipeNoteOutSchema
 */
export type PrivateRecipeNoteOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Note
     */
    note: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Order
     */
    order?: number;
};

/**
 * PrivateRecipeOutSchema
 */
export type PrivateRecipeOutSchema = {
    category: PrivateRecipeCategorieOutSchema;
    /**
     * Steps
     */
    steps?: Array<PrivateRecipeStepOutSchema>;
    /**
     * Ingredients
     */
    ingredients?: Array<PrivateRecipeIngredientOutSchema>;
    /**
     * Notes
     */
    notes?: Array<PrivateRecipeNoteOutSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Short Description
     */
    short_description?: string | null;
};

/**
 * PrivateRecipeStepOutSchema
 */
export type PrivateRecipeStepOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Order
     */
    order: number;
    /**
     * Instruction
     */
    instruction: string;
};

/**
 * AllergyInSchema
 */
export type AllergyInSchema = {
    /**
     * Sqid
     */
    sqid: string;
};

/**
 * IngredientInSchema
 */
export type IngredientInSchema = {
    /**
     * Allergy Sqids
     */
    allergy_sqids?: Array<string>;
    /**
     * Name Singular
     */
    name_singular: string;
    /**
     * Name Plural
     */
    name_plural: string;
};

/**
 * RecipeCategoryInSchema
 */
export type RecipeCategoryInSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name?: string | null;
};

/**
 * RecipeIngredientAltForAllergyInSchema
 */
export type RecipeIngredientAltForAllergyInSchema = {
    /**
     * Sqid
     */
    sqid?: string | null;
    /**
     * For Allergies
     */
    for_allergies?: Array<AllergyInSchema>;
    alternative_ingredient: IngredientInSchema;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit
     */
    unit?: string | null;
};

/**
 * RecipeIngredientInSchema
 */
export type RecipeIngredientInSchema = {
    /**
     * Sqid
     */
    sqid?: string | null;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit
     */
    unit?: string | null;
    ingredient: IngredientInSchema;
    /**
     * Ingredient Alternatives
     */
    ingredient_alternatives?: Array<RecipeIngredientAltForAllergyInSchema>;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * RecipeNoteInSchema
 */
export type RecipeNoteInSchema = {
    /**
     * Sqid
     */
    sqid?: string;
    /**
     * Order
     */
    order: number;
    /**
     * Note
     */
    note: string;
    /**
     * Type
     */
    type: string;
};

/**
 * RecipeStepInSchema
 */
export type RecipeStepInSchema = {
    /**
     * Sqid
     */
    sqid?: string | null;
    /**
     * Order
     */
    order: number;
    /**
     * Instruction
     */
    instruction: string;
};

/**
 * RecipeUpdateInSchema
 */
export type RecipeUpdateInSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Short Description
     */
    short_description?: string | null;
    category: RecipeCategoryInSchema;
    /**
     * Steps
     */
    steps?: Array<RecipeStepInSchema>;
    /**
     * Ingredients
     */
    ingredients?: Array<RecipeIngredientInSchema>;
    /**
     * Notes
     */
    notes?: Array<RecipeNoteInSchema>;
};

/**
 * AllergyOutSchema
 */
export type AllergyOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * IngredientOutSchema
 */
export type IngredientOutSchema = {
    /**
     * Allergies
     */
    allergies?: Array<AllergyOutSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name Singular
     */
    name_singular: string;
    /**
     * Name Plural
     */
    name_plural: string;
};

export type RecipesApiPrivateListPrivateRecipesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/private/recipes/recipes/';
};

export type RecipesApiPrivateListPrivateRecipesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipesApiPrivateCreatePrivateRecipeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Recipe Data
         */
        recipe_data: {
            [key: string]: unknown;
        };
    };
    url: '/private/recipes/recipes/';
};

export type RecipesApiPrivateCreatePrivateRecipeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipesApiPrivateDeletePrivateRecipeData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/private/recipes/recipes/{sqid}/';
};

export type RecipesApiPrivateDeletePrivateRecipeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipesApiPrivateGetPrivateRecipeDetailData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/private/recipes/recipes/{sqid}/';
};

export type RecipesApiPrivateGetPrivateRecipeDetailResponses = {
    /**
     * OK
     */
    200: PrivateRecipeOutSchema;
};

export type RecipesApiPrivateGetPrivateRecipeDetailResponse = RecipesApiPrivateGetPrivateRecipeDetailResponses[keyof RecipesApiPrivateGetPrivateRecipeDetailResponses];

export type RecipesApiPrivateUpdatePrivateRecipeData = {
    body: RecipeUpdateInSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/private/recipes/recipes/{sqid}/';
};

export type RecipesApiPrivateUpdatePrivateRecipeResponses = {
    /**
     * OK
     */
    200: PrivateRecipeOutSchema;
};

export type RecipesApiPrivateUpdatePrivateRecipeResponse = RecipesApiPrivateUpdatePrivateRecipeResponses[keyof RecipesApiPrivateUpdatePrivateRecipeResponses];

export type IngredientsApiPrivateGetIngredientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/private/ingredients/ingredients/';
};

export type IngredientsApiPrivateGetIngredientsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<IngredientOutSchema>;
};

export type IngredientsApiPrivateGetIngredientsResponse = IngredientsApiPrivateGetIngredientsResponses[keyof IngredientsApiPrivateGetIngredientsResponses];

export type IngredientsApiPrivateCreateIngredientData = {
    body: IngredientInSchema;
    path?: never;
    query?: never;
    url: '/private/ingredients/ingredients/';
};

export type IngredientsApiPrivateCreateIngredientResponses = {
    /**
     * Created
     */
    201: IngredientOutSchema;
};

export type IngredientsApiPrivateCreateIngredientResponse = IngredientsApiPrivateCreateIngredientResponses[keyof IngredientsApiPrivateCreateIngredientResponses];

export type IngredientsApiPrivateGetIngredientDetailData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/private/ingredients/ingredients/{sqid}/';
};

export type IngredientsApiPrivateGetIngredientDetailResponses = {
    /**
     * OK
     */
    200: IngredientOutSchema;
};

export type IngredientsApiPrivateGetIngredientDetailResponse = IngredientsApiPrivateGetIngredientDetailResponses[keyof IngredientsApiPrivateGetIngredientDetailResponses];

export type IngredientsApiPrivateUpdateIngredientData = {
    body: IngredientInSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/private/ingredients/ingredients/{sqid}/';
};

export type IngredientsApiPrivateUpdateIngredientResponses = {
    /**
     * OK
     */
    200: IngredientOutSchema;
};

export type IngredientsApiPrivateUpdateIngredientResponse = IngredientsApiPrivateUpdateIngredientResponses[keyof IngredientsApiPrivateUpdateIngredientResponses];

export type IngredientsApiPrivateGetAllergiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/private/ingredients/allergies/';
};

export type IngredientsApiPrivateGetAllergiesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<AllergyOutSchema>;
};

export type IngredientsApiPrivateGetAllergiesResponse = IngredientsApiPrivateGetAllergiesResponses[keyof IngredientsApiPrivateGetAllergiesResponses];
