// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type MutationOptions, queryOptions } from '@tanstack/svelte-query';

import { client } from '../client.gen';
import { ingredientsApiPrivateCreateIngredient, ingredientsApiPrivateGetAllergies, ingredientsApiPrivateGetIngredientDetail, ingredientsApiPrivateGetIngredients, ingredientsApiPrivateUpdateIngredient, type Options, recipesApiPrivateCreatePrivateRecipe, recipesApiPrivateDeletePrivateRecipe, recipesApiPrivateGetPrivateRecipeDetail, recipesApiPrivateListPrivateRecipes, recipesApiPrivateUpdatePrivateRecipe } from '../sdk.gen';
import type { IngredientsApiPrivateCreateIngredientData, IngredientsApiPrivateCreateIngredientResponse, IngredientsApiPrivateGetAllergiesData, IngredientsApiPrivateGetAllergiesResponse, IngredientsApiPrivateGetIngredientDetailData, IngredientsApiPrivateGetIngredientDetailResponse, IngredientsApiPrivateGetIngredientsData, IngredientsApiPrivateGetIngredientsResponse, IngredientsApiPrivateUpdateIngredientData, IngredientsApiPrivateUpdateIngredientResponse, RecipesApiPrivateCreatePrivateRecipeData, RecipesApiPrivateDeletePrivateRecipeData, RecipesApiPrivateGetPrivateRecipeDetailData, RecipesApiPrivateGetPrivateRecipeDetailResponse, RecipesApiPrivateListPrivateRecipesData, RecipesApiPrivateUpdatePrivateRecipeData, RecipesApiPrivateUpdatePrivateRecipeResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const recipesApiPrivateListPrivateRecipesQueryKey = (options?: Options<RecipesApiPrivateListPrivateRecipesData>) => createQueryKey('recipesApiPrivateListPrivateRecipes', options);

/**
 * List Private Recipes
 */
export const recipesApiPrivateListPrivateRecipesOptions = (options?: Options<RecipesApiPrivateListPrivateRecipesData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof recipesApiPrivateListPrivateRecipesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPrivateListPrivateRecipes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPrivateListPrivateRecipesQueryKey(options)
});

/**
 * Create Private Recipe
 */
export const recipesApiPrivateCreatePrivateRecipeMutation = (options?: Partial<Options<RecipesApiPrivateCreatePrivateRecipeData>>): MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateCreatePrivateRecipeData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateCreatePrivateRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPrivateCreatePrivateRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Private Recipe
 */
export const recipesApiPrivateDeletePrivateRecipeMutation = (options?: Partial<Options<RecipesApiPrivateDeletePrivateRecipeData>>): MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateDeletePrivateRecipeData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateDeletePrivateRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPrivateDeletePrivateRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const recipesApiPrivateGetPrivateRecipeDetailQueryKey = (options: Options<RecipesApiPrivateGetPrivateRecipeDetailData>) => createQueryKey('recipesApiPrivateGetPrivateRecipeDetail', options);

/**
 * Get Private Recipe Detail
 */
export const recipesApiPrivateGetPrivateRecipeDetailOptions = (options: Options<RecipesApiPrivateGetPrivateRecipeDetailData>) => queryOptions<RecipesApiPrivateGetPrivateRecipeDetailResponse, DefaultError, RecipesApiPrivateGetPrivateRecipeDetailResponse, ReturnType<typeof recipesApiPrivateGetPrivateRecipeDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPrivateGetPrivateRecipeDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPrivateGetPrivateRecipeDetailQueryKey(options)
});

/**
 * Update Private Recipe
 */
export const recipesApiPrivateUpdatePrivateRecipeMutation = (options?: Partial<Options<RecipesApiPrivateUpdatePrivateRecipeData>>): MutationOptions<RecipesApiPrivateUpdatePrivateRecipeResponse, DefaultError, Options<RecipesApiPrivateUpdatePrivateRecipeData>> => {
    const mutationOptions: MutationOptions<RecipesApiPrivateUpdatePrivateRecipeResponse, DefaultError, Options<RecipesApiPrivateUpdatePrivateRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPrivateUpdatePrivateRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ingredientsApiPrivateGetIngredientsQueryKey = (options?: Options<IngredientsApiPrivateGetIngredientsData>) => createQueryKey('ingredientsApiPrivateGetIngredients', options);

/**
 * Get Ingredients
 */
export const ingredientsApiPrivateGetIngredientsOptions = (options?: Options<IngredientsApiPrivateGetIngredientsData>) => queryOptions<IngredientsApiPrivateGetIngredientsResponse, DefaultError, IngredientsApiPrivateGetIngredientsResponse, ReturnType<typeof ingredientsApiPrivateGetIngredientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPrivateGetIngredients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPrivateGetIngredientsQueryKey(options)
});

/**
 * Create Ingredient
 */
export const ingredientsApiPrivateCreateIngredientMutation = (options?: Partial<Options<IngredientsApiPrivateCreateIngredientData>>): MutationOptions<IngredientsApiPrivateCreateIngredientResponse, DefaultError, Options<IngredientsApiPrivateCreateIngredientData>> => {
    const mutationOptions: MutationOptions<IngredientsApiPrivateCreateIngredientResponse, DefaultError, Options<IngredientsApiPrivateCreateIngredientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ingredientsApiPrivateCreateIngredient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ingredientsApiPrivateGetIngredientDetailQueryKey = (options: Options<IngredientsApiPrivateGetIngredientDetailData>) => createQueryKey('ingredientsApiPrivateGetIngredientDetail', options);

/**
 * Get Ingredient Detail
 */
export const ingredientsApiPrivateGetIngredientDetailOptions = (options: Options<IngredientsApiPrivateGetIngredientDetailData>) => queryOptions<IngredientsApiPrivateGetIngredientDetailResponse, DefaultError, IngredientsApiPrivateGetIngredientDetailResponse, ReturnType<typeof ingredientsApiPrivateGetIngredientDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPrivateGetIngredientDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPrivateGetIngredientDetailQueryKey(options)
});

/**
 * Update Ingredient
 */
export const ingredientsApiPrivateUpdateIngredientMutation = (options?: Partial<Options<IngredientsApiPrivateUpdateIngredientData>>): MutationOptions<IngredientsApiPrivateUpdateIngredientResponse, DefaultError, Options<IngredientsApiPrivateUpdateIngredientData>> => {
    const mutationOptions: MutationOptions<IngredientsApiPrivateUpdateIngredientResponse, DefaultError, Options<IngredientsApiPrivateUpdateIngredientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ingredientsApiPrivateUpdateIngredient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ingredientsApiPrivateGetAllergiesQueryKey = (options?: Options<IngredientsApiPrivateGetAllergiesData>) => createQueryKey('ingredientsApiPrivateGetAllergies', options);

/**
 * Get Allergies
 */
export const ingredientsApiPrivateGetAllergiesOptions = (options?: Options<IngredientsApiPrivateGetAllergiesData>) => queryOptions<IngredientsApiPrivateGetAllergiesResponse, DefaultError, IngredientsApiPrivateGetAllergiesResponse, ReturnType<typeof ingredientsApiPrivateGetAllergiesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPrivateGetAllergies({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPrivateGetAllergiesQueryKey(options)
});
