// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type MutationOptions, queryOptions } from '@tanstack/svelte-query';

import { client } from '../client.gen';
import { type Options, recipesApiPrivateCreateIngredient, recipesApiPrivateCreatePrivateRecipe, recipesApiPrivateDeletePrivateRecipe, recipesApiPrivateGetPrivateRecipeDetail, recipesApiPrivateListPrivateRecipes, recipesApiPrivateUpdatePrivateRecipe } from '../sdk.gen';
import type { RecipesApiPrivateCreateIngredientData, RecipesApiPrivateCreatePrivateRecipeData, RecipesApiPrivateDeletePrivateRecipeData, RecipesApiPrivateGetPrivateRecipeDetailData, RecipesApiPrivateGetPrivateRecipeDetailResponse, RecipesApiPrivateListPrivateRecipesData, RecipesApiPrivateUpdatePrivateRecipeData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const recipesApiPrivateListPrivateRecipesQueryKey = (options?: Options<RecipesApiPrivateListPrivateRecipesData>) => createQueryKey('recipesApiPrivateListPrivateRecipes', options);

/**
 * List Private Recipes
 */
export const recipesApiPrivateListPrivateRecipesOptions = (options?: Options<RecipesApiPrivateListPrivateRecipesData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof recipesApiPrivateListPrivateRecipesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPrivateListPrivateRecipes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPrivateListPrivateRecipesQueryKey(options)
});

/**
 * Create Private Recipe
 */
export const recipesApiPrivateCreatePrivateRecipeMutation = (options?: Partial<Options<RecipesApiPrivateCreatePrivateRecipeData>>): MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateCreatePrivateRecipeData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateCreatePrivateRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPrivateCreatePrivateRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Private Recipe
 */
export const recipesApiPrivateDeletePrivateRecipeMutation = (options?: Partial<Options<RecipesApiPrivateDeletePrivateRecipeData>>): MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateDeletePrivateRecipeData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateDeletePrivateRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPrivateDeletePrivateRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const recipesApiPrivateGetPrivateRecipeDetailQueryKey = (options: Options<RecipesApiPrivateGetPrivateRecipeDetailData>) => createQueryKey('recipesApiPrivateGetPrivateRecipeDetail', options);

/**
 * Get Private Recipe Detail
 */
export const recipesApiPrivateGetPrivateRecipeDetailOptions = (options: Options<RecipesApiPrivateGetPrivateRecipeDetailData>) => queryOptions<RecipesApiPrivateGetPrivateRecipeDetailResponse, DefaultError, RecipesApiPrivateGetPrivateRecipeDetailResponse, ReturnType<typeof recipesApiPrivateGetPrivateRecipeDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPrivateGetPrivateRecipeDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPrivateGetPrivateRecipeDetailQueryKey(options)
});

/**
 * Update Private Recipe
 */
export const recipesApiPrivateUpdatePrivateRecipeMutation = (options?: Partial<Options<RecipesApiPrivateUpdatePrivateRecipeData>>): MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateUpdatePrivateRecipeData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateUpdatePrivateRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPrivateUpdatePrivateRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Ingredient
 */
export const recipesApiPrivateCreateIngredientMutation = (options?: Partial<Options<RecipesApiPrivateCreateIngredientData>>): MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateCreateIngredientData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateCreateIngredientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPrivateCreateIngredient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
