# Generated by Django 2.2.7 on 2019-11-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HapMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetails',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
