# Generated by Django 3.0.2 on 2020-02-22 18:24

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('HapMap', '0002_auto_20191122_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
