# Generated by Django 3.0.2 on 2020-02-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HapMap', '0002_auto_20191122_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allergie_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Alt_Ingeredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alt_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HapMap.Ingredient')),
                ('for_allergie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HapMap.Alergie')),
                ('for_recipe_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HapMap.RecipeDetails')),
            ],
        ),
    ]
