// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { IngredientsApiGetIngredientsData, IngredientsApiGetIngredientsResponses, RecipesApiGetRecipeDetailData, RecipesApiGetRecipeDetailResponses, RecipesApiGetRecipesData, RecipesApiGetRecipesResponses, RecipesApiSearchRecipesData, RecipesApiSearchRecipesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Ingredients
 */
export const ingredientsApiGetIngredients = <ThrowOnError extends boolean = false>(options?: Options<IngredientsApiGetIngredientsData, ThrowOnError>) => (options?.client ?? client).get<IngredientsApiGetIngredientsResponses, unknown, ThrowOnError>({ url: '/ingredients/', ...options });

/**
 * Get Recipes
 */
export const recipesApiGetRecipes = <ThrowOnError extends boolean = false>(options?: Options<RecipesApiGetRecipesData, ThrowOnError>) => (options?.client ?? client).get<RecipesApiGetRecipesResponses, unknown, ThrowOnError>({ url: '/recipes/', ...options });

/**
 * Get Recipe Detail
 */
export const recipesApiGetRecipeDetail = <ThrowOnError extends boolean = false>(options: Options<RecipesApiGetRecipeDetailData, ThrowOnError>) => (options.client ?? client).get<RecipesApiGetRecipeDetailResponses, unknown, ThrowOnError>({ url: '/recipes/{sqid}/', ...options });

/**
 * Search Recipes
 */
export const recipesApiSearchRecipes = <ThrowOnError extends boolean = false>(options: Options<RecipesApiSearchRecipesData, ThrowOnError>) => (options.client ?? client).post<RecipesApiSearchRecipesResponses, unknown, ThrowOnError>({ url: '/recipes/search/', ...options });
