// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * RecipeFilterSchema
 */
export type RecipeFilterSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Created By
     */
    created_by?: string | null;
};

/**
 * AllergyOutSchema
 */
export type AllergyOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * RecipeCategoryOutSchema
 */
export type RecipeCategoryOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * RecipeListOutSchema
 */
export type RecipeListOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Short Description
     */
    short_description: string;
    category: RecipeCategoryOutSchema;
    /**
     * Includes Allergies
     */
    includes_allergies: Array<AllergyOutSchema>;
    /**
     * Created At
     */
    created_at: string;
    created_by: UserOutSchema;
};

/**
 * UserOutSchema
 */
export type UserOutSchema = {
    /**
     * Username
     */
    username: string;
};

/**
 * AlternativeOutSchema
 */
export type AlternativeOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    ingredient: IngredientOutSchema;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit
     */
    unit: string;
};

/**
 * IngredientOutSchema
 */
export type IngredientOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name Singular
     */
    name_singular: string;
    /**
     * Name Plural
     */
    name_plural: string;
    /**
     * Allergies
     */
    allergies?: Array<AllergyOutSchema>;
};

/**
 * RecipeIngredientOutSchema
 */
export type RecipeIngredientOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    ingredient: IngredientOutSchema;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit
     */
    unit: string;
    /**
     * Allergy
     */
    allergy?: string;
    ingredient_alternative?: AlternativeOutSchema;
};

/**
 * RecipeNoteOutSchema
 */
export type RecipeNoteOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Note
     */
    note: string;
    /**
     * Type
     */
    type: string;
    /**
     * Order
     */
    order: number;
};

/**
 * RecipeOutSchema
 */
export type RecipeOutSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Includes Allergies
     */
    includes_allergies?: Array<AllergyOutSchema>;
    /**
     * Description
     */
    description: string;
    /**
     * Short Description
     */
    short_description: string;
    category: RecipeCategoryOutSchema;
    /**
     * Notes
     */
    notes?: Array<RecipeNoteOutSchema>;
    /**
     * Ingredients
     */
    ingredients?: Array<RecipeIngredientOutSchema>;
};

export type IngredientsApiGetIngredientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ingredients/';
};

export type IngredientsApiGetIngredientsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipesApiGetRecipesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name
         */
        name?: string | null;
        /**
         * Created By
         */
        created_by?: string | null;
    };
    url: '/recipes/';
};

export type RecipesApiGetRecipesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<RecipeListOutSchema>;
};

export type RecipesApiGetRecipesResponse = RecipesApiGetRecipesResponses[keyof RecipesApiGetRecipesResponses];

export type RecipesApiGetRecipeDetailData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/recipes/{sqid}/';
};

export type RecipesApiGetRecipeDetailResponses = {
    /**
     * OK
     */
    200: RecipeOutSchema;
};

export type RecipesApiGetRecipeDetailResponse = RecipesApiGetRecipeDetailResponses[keyof RecipesApiGetRecipeDetailResponses];

export type RecipesApiSearchRecipesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
    };
    url: '/recipes/search/';
};

export type RecipesApiSearchRecipesResponses = {
    /**
     * OK
     */
    200: unknown;
};
