// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type MutationOptions, queryOptions } from '@tanstack/svelte-query';

import { client } from '../client.gen';
import { camplistsApiGetKamplijst, camplistsApiListKamplijsts, ingredientsApiPublicGetAllergies, ingredientsApiPublicGetIngredientDetail, ingredientsApiPublicGetIngredients, type Options, recipesApiPublicGetCategories, recipesApiPublicGetRecipeDetail, recipesApiPublicGetRecipes, recipesApiPublicSearchRecipes } from '../sdk.gen';
import type { CamplistsApiGetKamplijstData, CamplistsApiListKamplijstsData, IngredientsApiPublicGetAllergiesData, IngredientsApiPublicGetAllergiesResponse, IngredientsApiPublicGetIngredientDetailData, IngredientsApiPublicGetIngredientDetailResponse, IngredientsApiPublicGetIngredientsData, IngredientsApiPublicGetIngredientsResponse, RecipesApiPublicGetCategoriesData, RecipesApiPublicGetCategoriesResponse, RecipesApiPublicGetRecipeDetailData, RecipesApiPublicGetRecipeDetailResponse, RecipesApiPublicGetRecipesData, RecipesApiPublicGetRecipesResponse, RecipesApiPublicSearchRecipesData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const ingredientsApiPublicGetIngredientsQueryKey = (options?: Options<IngredientsApiPublicGetIngredientsData>) => createQueryKey('ingredientsApiPublicGetIngredients', options);

/**
 * Get Ingredients
 */
export const ingredientsApiPublicGetIngredientsOptions = (options?: Options<IngredientsApiPublicGetIngredientsData>) => queryOptions<IngredientsApiPublicGetIngredientsResponse, DefaultError, IngredientsApiPublicGetIngredientsResponse, ReturnType<typeof ingredientsApiPublicGetIngredientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPublicGetIngredients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPublicGetIngredientsQueryKey(options)
});

export const ingredientsApiPublicGetIngredientDetailQueryKey = (options: Options<IngredientsApiPublicGetIngredientDetailData>) => createQueryKey('ingredientsApiPublicGetIngredientDetail', options);

/**
 * Get Ingredient Detail
 */
export const ingredientsApiPublicGetIngredientDetailOptions = (options: Options<IngredientsApiPublicGetIngredientDetailData>) => queryOptions<IngredientsApiPublicGetIngredientDetailResponse, DefaultError, IngredientsApiPublicGetIngredientDetailResponse, ReturnType<typeof ingredientsApiPublicGetIngredientDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPublicGetIngredientDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPublicGetIngredientDetailQueryKey(options)
});

export const ingredientsApiPublicGetAllergiesQueryKey = (options?: Options<IngredientsApiPublicGetAllergiesData>) => createQueryKey('ingredientsApiPublicGetAllergies', options);

/**
 * Get Allergies
 */
export const ingredientsApiPublicGetAllergiesOptions = (options?: Options<IngredientsApiPublicGetAllergiesData>) => queryOptions<IngredientsApiPublicGetAllergiesResponse, DefaultError, IngredientsApiPublicGetAllergiesResponse, ReturnType<typeof ingredientsApiPublicGetAllergiesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPublicGetAllergies({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPublicGetAllergiesQueryKey(options)
});

export const recipesApiPublicGetRecipesQueryKey = (options?: Options<RecipesApiPublicGetRecipesData>) => createQueryKey('recipesApiPublicGetRecipes', options);

/**
 * Get Recipes
 */
export const recipesApiPublicGetRecipesOptions = (options?: Options<RecipesApiPublicGetRecipesData>) => queryOptions<RecipesApiPublicGetRecipesResponse, DefaultError, RecipesApiPublicGetRecipesResponse, ReturnType<typeof recipesApiPublicGetRecipesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPublicGetRecipes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPublicGetRecipesQueryKey(options)
});

export const recipesApiPublicGetRecipeDetailQueryKey = (options: Options<RecipesApiPublicGetRecipeDetailData>) => createQueryKey('recipesApiPublicGetRecipeDetail', options);

/**
 * Get Recipe Detail
 */
export const recipesApiPublicGetRecipeDetailOptions = (options: Options<RecipesApiPublicGetRecipeDetailData>) => queryOptions<RecipesApiPublicGetRecipeDetailResponse, DefaultError, RecipesApiPublicGetRecipeDetailResponse, ReturnType<typeof recipesApiPublicGetRecipeDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPublicGetRecipeDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPublicGetRecipeDetailQueryKey(options)
});

/**
 * Search Recipes
 */
export const recipesApiPublicSearchRecipesMutation = (options?: Partial<Options<RecipesApiPublicSearchRecipesData>>): MutationOptions<unknown, DefaultError, Options<RecipesApiPublicSearchRecipesData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RecipesApiPublicSearchRecipesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPublicSearchRecipes({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const recipesApiPublicGetCategoriesQueryKey = (options?: Options<RecipesApiPublicGetCategoriesData>) => createQueryKey('recipesApiPublicGetCategories', options);

/**
 * Get Categories
 */
export const recipesApiPublicGetCategoriesOptions = (options?: Options<RecipesApiPublicGetCategoriesData>) => queryOptions<RecipesApiPublicGetCategoriesResponse, DefaultError, RecipesApiPublicGetCategoriesResponse, ReturnType<typeof recipesApiPublicGetCategoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPublicGetCategories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPublicGetCategoriesQueryKey(options)
});

export const camplistsApiListKamplijstsQueryKey = (options?: Options<CamplistsApiListKamplijstsData>) => createQueryKey('camplistsApiListKamplijsts', options);

/**
 * List Kamplijsts
 */
export const camplistsApiListKamplijstsOptions = (options?: Options<CamplistsApiListKamplijstsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof camplistsApiListKamplijstsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await camplistsApiListKamplijsts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: camplistsApiListKamplijstsQueryKey(options)
});

export const camplistsApiGetKamplijstQueryKey = (options: Options<CamplistsApiGetKamplijstData>) => createQueryKey('camplistsApiGetKamplijst', options);

/**
 * Get Kamplijst
 */
export const camplistsApiGetKamplijstOptions = (options: Options<CamplistsApiGetKamplijstData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof camplistsApiGetKamplijstQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await camplistsApiGetKamplijst({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: camplistsApiGetKamplijstQueryKey(options)
});
