// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type MutationOptions, queryOptions } from '@tanstack/svelte-query';

import { client } from '../client.gen';
import { ingredientsApiGetIngredients, type Options, recipesApiGetRecipeDetail, recipesApiGetRecipes, recipesApiSearchRecipes } from '../sdk.gen';
import type { IngredientsApiGetIngredientsData, RecipesApiGetRecipeDetailData, RecipesApiGetRecipeDetailResponse, RecipesApiGetRecipesData, RecipesApiGetRecipesResponse, RecipesApiSearchRecipesData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const ingredientsApiGetIngredientsQueryKey = (options?: Options<IngredientsApiGetIngredientsData>) => createQueryKey('ingredientsApiGetIngredients', options);

/**
 * Get Ingredients
 */
export const ingredientsApiGetIngredientsOptions = (options?: Options<IngredientsApiGetIngredientsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof ingredientsApiGetIngredientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiGetIngredients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiGetIngredientsQueryKey(options)
});

export const recipesApiGetRecipesQueryKey = (options?: Options<RecipesApiGetRecipesData>) => createQueryKey('recipesApiGetRecipes', options);

/**
 * Get Recipes
 */
export const recipesApiGetRecipesOptions = (options?: Options<RecipesApiGetRecipesData>) => queryOptions<RecipesApiGetRecipesResponse, DefaultError, RecipesApiGetRecipesResponse, ReturnType<typeof recipesApiGetRecipesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiGetRecipes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiGetRecipesQueryKey(options)
});

export const recipesApiGetRecipeDetailQueryKey = (options: Options<RecipesApiGetRecipeDetailData>) => createQueryKey('recipesApiGetRecipeDetail', options);

/**
 * Get Recipe Detail
 */
export const recipesApiGetRecipeDetailOptions = (options: Options<RecipesApiGetRecipeDetailData>) => queryOptions<RecipesApiGetRecipeDetailResponse, DefaultError, RecipesApiGetRecipeDetailResponse, ReturnType<typeof recipesApiGetRecipeDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiGetRecipeDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiGetRecipeDetailQueryKey(options)
});

/**
 * Search Recipes
 */
export const recipesApiSearchRecipesMutation = (options?: Partial<Options<RecipesApiSearchRecipesData>>): MutationOptions<unknown, DefaultError, Options<RecipesApiSearchRecipesData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RecipesApiSearchRecipesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiSearchRecipes({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
