# Generated by Django 3.0.2 on 2020-03-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergie_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=255)),
                ('categorie_img', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('allergies', models.ManyToManyField(blank=True, null=True, to='recipebook.Alergie')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=255)),
                ('recipe_description', models.TextField(blank=True, null=True)),
                ('recipe_img', models.CharField(blank=True, max_length=255, null=True)),
                ('recipe_tip', models.TextField(blank=True)),
                ('recipe_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipebook.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Webshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webshop_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.Ingredient')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.Recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('ingredient_description', models.TextField(blank=True, null=True)),
                ('ingredient_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ingredient_ammount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ingredient_webshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipebook.Webshop')),
            ],
        ),
        migrations.CreateModel(
            name='Alt_Ingeredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alt_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.Ingredient')),
                ('for_allergie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.Alergie')),
                ('for_recipe_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.RecipeDetail')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.Unit')),
            ],
        ),
    ]
